InsertDataUsingDapper/Models/Bank.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InsertDataUsingDapper.Models
{
  
    public class Bank
    {
        public int BankId { get; set; }
        [Required(ErrorMessage ="please fill the name")]
        public string Name { get; set; }

       
        [Display(Name ="Sales Amount")]
        public string Sales_Amount { get; set; }


        [DataType(DataType.Date)]
        [Display(Name ="Date of Sales")]
        public DateTime Date_Of_Sales { get; set; }

        [Display(Name ="Payment Type")]
        public string Payment_Type { get; set; }

        [Display(Name ="Cash Bank Ledger")]
        public string cash_Bank_Ledger { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
    }
}

InsertDataUsingDapper/Models/DapperORM.cs
using Dapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace InsertDataUsingDapper.Models
{
    public static class DapperORM
    {
        private static string connectionString = @"Data Source=DESKTOP-OOFHTK8\SQLEXPRESS;Initial Catalog=DapperKGE;Integrated Security=True";
        public static void ExecutedWithoutReturn(string procedureName, DynamicParameters param=null)
        {
            using(SqlConnection sqlcon=new SqlConnection(connectionString))
            {
                sqlcon.Open();
                sqlcon.Execute(procedureName, param, commandType: System.Data.CommandType.StoredProcedure);
            }
        }

        public static T ExecuteReturnScalar<T>(string procedureName,DynamicParameters param=null)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                return (T)Convert.ChangeType(sqlcon.ExecuteScalar(procedureName, param, commandType: System.Data.CommandType.StoredProcedure),typeof(T));
            }
        }

        public static IEnumerable<T> ReturnList<T>(string procedureName, DynamicParameters param=null)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                return sqlcon.Query<T>(procedureName, param, commandType: System.Data.CommandType.StoredProcedure);
            }
        }
    }
}

InsertDataUsingDapper/Controllers/BankController.cs
using Dapper;
using InsertDataUsingDapper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace InsertDataUsingDapper.Controllers
{
    public class BankController : Controller
    {
        // GET: Bank
        public ActionResult Index()
        {
            return View(DapperORM.ReturnList<Bank>("BankDetailsViewAll",null));
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult AddOrEdit(Bank bank)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@BankId", bank.BankId);
            param.Add("@Name", bank.Name);
            param.Add("@Sales_Amount", bank.Sales_Amount);
            param.Add("@Date_Of_Sales", bank.Date_Of_Sales);
            param.Add("@Payment_Type", bank.Payment_Type);
            param.Add("@cash_Bank_Ledger", bank.cash_Bank_Ledger);
            param.Add("@RefNo", bank.RefNo);
            param.Add("@Status", bank.Status);
            DapperORM.ExecutedWithoutReturn("BankDetailsAddorEdit", param);

            return RedirectToAction("Index");
        }
    }
}

InsertDataUsingDapper/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsertDataUsingDapper.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

InsertDataUsingDapper/Views/Bank/AddOrEdit.cshtml
@model InsertDataUsingDapper.Models.Bank

@{
    ViewBag.Title = "AddOrEdit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Bank</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.BankId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sales_Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sales_Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sales_Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Of_Sales, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Of_Sales, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Payment_Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Payment_Type, new { htmlAttribute = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Payment_Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cash_Bank_Ledger, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cash_Bank_Ledger, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cash_Bank_Ledger, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RefNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RefNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RefNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsertDataUsingDapper/Views/Bank/Index.cshtml
@model IEnumerable<InsertDataUsingDapper.Models.Bank>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<style>
    table,th,td{
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: center;
        text-transform: capitalize;
    }
    th{
        text-align: center;
       
    }
</style>

<p>
    @Html.ActionLink("Create New", "AddOrEdit","Bank")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sales_Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Of_Sales)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Payment_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cash_Bank_Ledger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RefNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Sales_Amount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Date_Of_Sales)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Payment_Type)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.cash_Bank_Ledger)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RefNo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    @*<td>
        @Html.ActionLink("Edit", "Edit", new { id = item.BankId }) |
        @Html.ActionLink("Details", "Details", new { id = item.BankId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.BankId })
    </td>*@
</tr>
}

</table>

InsertDataUsingDapper/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InsertDataUsingDapper/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

InsertDataUsingDapper/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

InsertDataUsingDapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Form", "AddOrEdit", "Bank")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>